#OBJS specifies which files to compile as part of the project
OBJS = Main.cpp

#OBJ_NAME specifies the name of our exectuable
OBJ_NAME = Game

#This is the target that compiles our executable
all :
	g++ src/$(OBJS) -IC:\SDL2\include -LC:\SDL2\lib -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -o $(OBJ_NAME)